# Pandas Notes

Here I upload whatever I learned about Pandas

## Basics Codes

There are some basic codes on reading and displaying a dataframe:

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], columns=['A', 'B', 'C'], index=['row1', 'row2', 'row3', 'row4'])

In [2]:
df.head() # shows the first 5 rows of the dataframe by default
df.head(2) # shows the first 2 rows of the dataframe

      A  B  C
row1  1  2  3
row2  4  5  6

In [3]:
df.tail() # shows the last 5 rows of the dataframe by default
df.tail(2) # shows the last 2 rows of the dataframe

       A   B   C
row3   7   8   9
row4  10  11  12