# Pandas Notes

Here I upload whatever I learned about Pandas

## Basics Codes

There are some basic codes on reading and displaying a dataframe:

In [20]:
import pandas as pd
import numpy as np

df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], columns=['A', 'B', 'C'], index=['row1', 'row2', 'row3', 'row4'])

In [21]:
df.head() # shows the first 5 rows of the dataframe by default
df.head(2) # shows the first 2 rows of the dataframe

      A  B  C
row1  1  2  3
row2  4  5  6

In [22]:
df.tail() # shows the last 5 rows of the dataframe by default
df.tail(2) # shows the last 2 rows of the dataframe

       A   B   C
row3   7   8   9
row4  10  11  12

In [23]:
df.info() # shows a concise summary of the dataframe, including the number of non-null values, data types, and memory usage
df.describe() # shows summary statistics of the dataframe, including count, mean, standard deviation, minimum, and maximum values for each column

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, row1 to row4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   B       4 non-null      int64
 2   C       4 non-null      int64
dtypes: int64(3)
memory usage: 128.0+ bytes

               A          B          C
count   4.000000   4.000000   4.000000
mean    5.500000   6.500000   7.500000
std     3.872983   3.872983   3.872983
min     1.000000   2.000000   3.000000
25%     3.250000   4.250000   5.250000
50%     5.500000   6.500000   7.500000
75%     7.750000   8.750000   9.750000
max    10.000000  11.000000  12.000000

In [24]:
df.columns.tolist() # shows the column names of the dataframe
df.index.tolist() # shows the index labels of the dataframe

['row1', 'row2', 'row3', 'row4']

## Loading DataFrames from Files

There are lighter data frames beside .csv like .feather or .parquest